<div id="slider_wrapper2">
    <div class="wrap">

        <h1>About Us</h1>

    </div>
</div>

<div class="clear"></div>

<div class="content" style="background: transparent">
    <div class="wrap" style="padding: 10px;">

        <h3>Why LaundryWala</h3>

        <p>Today, Many people are hesitant to take their clothes to local Laundromats or dhobis because they fear that optimal care and hygiene may not be maintained and that their clothes may either get discolored, torn or misplaced. Haggling with dhobis over their ever changing prices is another pain.</p>
        <p>Everyone has a penchant for expensive clothes, with exquisite designs and fabric, that makes them stand apart. Why should you then settle even for the second best when it comes to laundering them?</p>
        <div class="clear"></div>
        <div class="divider"></div>

        <h3>What does LaundryWala do</h3>
        <p>LaundryWala is a Noida based online on-demand laundry service that aims at providing high quality laundry services coupled with customized experience and express delivery. “We use Latest technology machines and internationally standardized chemicals for quality cleaning. With an added feature of online ordering and free pick-up and delivery within 24 hours, we expect to reach every household in our vicinity”</p>
        <p>We provide washing, dry cleaning, steam ironing and other value added services in Noida to make your life free of laundry hassles.</p>
        <p>Our staff consists of experts who have huge experience and knowledge of different types of fabrics and garments and know how to treat them.</p>
        <p>We ensure that we find a smile on your face with every service that we provide.</p>








        <div class="clear"></div>

    </div>
</div>

<div class="blue-bar">

</div>