<div id="slider_wrapper2">
    <div class="wrap">

        <h1>Contact</h1>

    </div>
</div>

<div class="clear"></div>

<div class="content" style="background:transparent">
    <div class="wrap" style="background: transparent; padding: 10px;">

        <iframe id="google_map" style="pointer-events:none" src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d448182.50738077075!2d77.0932634!3d28.646965499999997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sA-109Q%2CSecond+Floor%2CSector-80%2CNoida-201305!5e0!3m2!1sen!2sin!4v1417004693415"></iframe>

        <div class="clear"></div>
        <div class="divider"></div>

        <div class="sidebar-left">
            <h3>Contact Info</h3>

            <ul>
                <li><i class="icon-home"></i>A-109Q,Second Floor,Sector-80,Noida-201305</li>
                <li><i class="icon-envelope"></i>info@laundrywala.co.in</li>
                <li><i class="icon-phone"></i>9953180071</li>
                <li><i class="icon-google-plus-sign"></i></li>
                <li><i class="icon-twitter-sign"></i>twitter.com/LaundryWala</li>
                <li><i class="icon-facebook-sign"></i>facebook.com/LaundryWala</li>
            </ul>

            <div class="clear"></div>
        </div>

        <div class="content-right">
            <h3>Drop Us A Line!</h3>
            <div id='contact_alert' style="display: none;"></div>

            <div class="clear"></div>
            <div class="space2"></div>

            <div id="contactform">
                <table>
                    <tr>
                        <td><input type="text" id="name" class="contact_name" name="name" placeholder="Your Name" /></td>
                    </tr>
                    <tr>
                        <td><input type="text" id="email" class="contact_email" name="email" placeholder="Your Email Address" /></td>
                    </tr>
                    <tr>
                        <td><textarea id="message" placeholder="Your Message"  class="contact_message"name="message" rows="10" cols="20"></textarea></td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" value="Send" id="contact_details" class="button" />
                            <!--<input type="reset" value="Reset" class="button" />-->
                        </td>
                    </tr>
                </table>
                <p class="success" style="display:none">Your message has been sent successfully.</p>
                <p class="error error-name" style="display:none">Your Name must be longer than 1 character.</p>
                <p class="error error-email" style="display:none">Your Email must be valid</p>
                <p class="error error-message" style="display:none">Your Message must be longer than 10 characters.</p>
            </div>

        </div>

        <div class="clear"></div>

    </div>
</div>

<div class="blue-bar">

</div>