<div id="slider_wrapper2">
    <div class="wrap" style="margin-top:120px;">

        <h1>FAQs</h1>

    </div>
</div>
<div class="faq-container" >
    <div id="accordion">
        <p class="accordion_header"><i class="icon-time"></i>What are your store hours? </p>
        <div>
            <p>We really don’t operate as a store yet. However if need arises we will have one. Till then you can avail our online booking with the free pickup and drop services.</p>
        </div>
        <p class="accordion_header"><i class="icon-hdd"></i>Do you have large machines? </p>
        <div>
            <p>Yes, the largest machines in the area. We have super large top of the line machines that can handle all your large items, comforters, blankets etc....</p>
        </div>
        <p class="accordion_header"><i class="icon-rocket"></i>Who is LaundryWala? </p>
        <div>
            <p>LaundryWala is the premiere laundry service in your area, where we reach people through door to door service.LaundryWala aims at providing high quality laundry services coupled with customized experience and express delivery. “We use Latest technology machines and internationally standardized chemicals for quality cleaning. With an added feature of online ordering and free pick-up and delivery within 24 hours, we expect to reach every household in our vicinity”.<br/><br/>We provide washing, dry cleaning, steam ironing and other value added services in Noida to make your life free of laundry hassles</p>
        </div>
        <p class="accordion_header"><i class="icon-rocket"></i>Who uses your Pickup & delivery services? </p>
        <div>
            <p>Really everyone. Our customers range from college students to busy professionals to seniors! Our service is for people who want to free-up time from a tedious and labour intensive task.</p>
        </div>
        <p class="accordion_header"><i class="icon-rocket"></i>What about dry cleaning? </p>
        <div>
            <p>Yes, we do offer these services as a convenience and for one-stop-shopping for our customers at very competitive prices. Please identify and place those items in a separate bag.</p>
        </div>
        <p class="accordion_header"><i class="icon-rocket"></i>Can I pay per wash?  </p>
        <div>
            <p>Yes, the cost as per the garment/cloth. Please check our price listing page.</p>
        </div>
        <p class="accordion_header"><i class="icon-question"></i>Are my clothes mixed with other orders?  </p>
        <div>
            <p>No, each customers clothing is done separately.</p>
        </div>
        <p class="accordion_header"><i class="icon-question"></i>How do I sign up?   </p>
        <div>
            <p>You can signup via our web portal.</p>
        </div>
        <p class="accordion_header"><i class="icon-book"></i>Do I need to separate my clothes before pickup?   </p>
        <div>
            <p>No, our experienced professionals will take care of this for you. If you have any delicates or special needs, just place them in a small plastic bag with a note.</p>
        </div>
        <p class="accordion_header"><i class="icon-book"></i>How much laundry can I have picked up each week?    </p>
        <div>
            <p>There is no maximum. We are made for this.</p>
        </div>
        <p class="accordion_header"><i class="icon-book"></i>How do I get my LaundryWala bag? </p>
        <div>
            <p>Your first order will be delivered in your new bag, it is yours for keeps.</p>
        </div>
        <p class="accordion_header"><i class="icon-book"></i>How do I let you know about my preferences?  </p>
        <div>
            <p>You can easily specify your personal preferences by including a note in with your bag of items or by typing your request in the Special Instructions field of the order screen when you place your order online</p>
        </div>
    </div> 
</div>

<div class="blue-bar">

</div>