
<?php
$orderMapper = new Application_Model_OrdersMapper();
$order_ids = $this->orderids;

$serviceMasterMapper = new Application_Model_ServiceMasterMapper();

$ids = explode(",", $order_ids);
?>
<?php if ($ids): ?>
    <?php foreach ($ids as $order_id): ?>
        <?php $order = $orderMapper->getOrderById($order_id); ?>
        <?php if ($order): ?>
            <div class="col-sm-4">
                <div class="print" style="width: 90mm;margin-bottom:30px;">
                    <div style="font-size: 34px;width: inherit;text-align: center;letter-spacing: 5;margin-bottom: 13px;"></div>
                    <div class="deliverdetails" style="border: 1px solid;">
                        <div style="text-align: center">
                            <img src="<?php echo $this->baseUrl(); ?>/front/images/test.png" style="width: 234px;"/>
                        </div><br/>

                        <?php
                        $user_fname = $order->__get("user_fname");
                        $user_lname = $order->__get("user_lname");
                        $address = $order->__get("user_address");
                        $city = $order->__get("address_city");
                        $state = $order->__get("address_state");
                        $pincode = $order->__get("address_pincode");
                        $order_id_new = $order->__get("order_id");
                        $date = $order->__get("timestamp");
                        $number = $order->__get("user_phn_number");
                        $method = $order->__get("payment_method");
                        $total = $order->__get("order_total");
                        $delivery_type = $order->__get("delivery_type");
                        $serviceMaster = $serviceMasterMapper->getServiceMasterById($order->__get("service"));
                        if ($serviceMaster)
                            $service_type = $serviceMaster->service_name;
                        ?>
                        <table style="width: 100%;">
                            <tr>
                                <td style="text-align:left;"><strong>Invoice No #</strong></td>
                                <td style=""><?php echo $order_id; ?></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><strong>Customer Name</strong></td>
                                <td style=""><?php echo $user_fname . " " . $user_lname; ?></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><strong>Address</strong></td>
                                <td style=""><?php echo $address . "," . $city . "," . $state; ?></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><strong>Phone No</strong></td>
                                <td style=""><?php echo $number; ?></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><strong>Booking Date</strong></td>
                                <td style=""><?php
                                    $zend_date = new Zend_Date($date, "dd MMM yyyy");
                                    echo $zend_date->toString("dd MMM yyyy");
                                    ?></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><strong>Payment Method</strong></td>
                                <td style=""><?php echo $method; ?></td>
                            </tr>
                            <tr>
                            <tr>
                                <td style="text-align:left;"><strong>Delivery Type</strong></td>
                                <td style=""><?php echo $delivery_type; ?></td>
                            </tr>
                            <tr>
                            <tr>
                                <td style="text-align:left;"><strong>Service Type</strong></td>
                                <td style=""><?php
                                    if ($service_type == "Dry Cleaning") {
                                        echo "DC";
                                    } else {
                                        echo "WH";
                                    }
                                    ?></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><strong>Total Amount Due</strong></td>
                                <?php if ($order->__get("discount_price") != NULL): ?>
                                    <td style="">Rs.<?php echo $order->__get("revised_price"); ?></td>
                                <?php else : ?>
                                    <td style="">Rs.<?php echo $total; ?></td>
                                <?php endif; ?>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><strong>Total Pieces</strong></td>
                                <td style=""><?php
                                $qty = 0;
                                $orderItemsMapper = new Application_Model_OrderItemsMapper();
                                $items = $orderItemsMapper->getOrderItemByOrderId($order_id);
                                if ($items) {
                                    foreach ($items as $item) {
                                        $qty += $item->__get("quantity");
                                    }
                                }
                                echo $qty;
                                ?></td>
                            </tr>
                        </table>

                        <div class="items" style="margin-top: 10px;border: 1px solid; min-height: 109px;">
                            <div style="text-align:center"><strong>Order Details</strong></div>

                            <table style="width: 100%;">
                                <tr>
                                    <th style="text-align: left;">Type</th>
                                    <th style="text-align: left;">Particular's</th>
                                    <th style="text-align: left;">Qty</th>
                                    <th style="text-align: left;">Price</th>
                                </tr>
                                <?php
                                $i = 1;
                                $total = 0;
                                $orderItemsMapper = new Application_Model_OrderItemsMapper();
                                $items = $orderItemsMapper->getOrderItemByOrderId($order_id);
                                if ($items):
                                    foreach ($items as $item):
                                        ?>
                                        <tr>
                                            <td>
                                                <?php
                                                if ($service_type == "Dry Cleaning") {
                                                    echo "DC";
                                                } else {
                                                    echo "WH";
                                                }
                                                ?>
                                            </td>
                                            <td style="text-align:left;">
                                                <?php
                                                $itemsMapper = new Application_Model_ItemsMapper();
                                                $item_name = $itemsMapper->getItemById($item->__get("item_id"));
                                                if ($item_name) {
                                                    echo $item_name->__get("item_name");
                                                } else {
                                                    echo "None";
                                                }
                                                ?>
                                            </td>
                                            <td style="text-align:left;">
                                                <?php
                                                echo $item->__get("quantity");
                                                ?>
                                            </td>
                                            <td style="text-align:left;">Rs.
                                                <?php
                                                echo $item->__get("total_price");
                                                $total += $item->__get("total_price");
                                                ?>
                                            </td>


                                        </tr>

                                        <?php
                                    endforeach;
                                endif;
                                ?>
                                <tr></tr>
                                <?php if ($total <= 100): ?>
                                    <tr>
                                        <td></td>
                                        <td></td>

                                        <td style="text-align: center;"><strong>SubTotal</strong></td>
                                        <td style="text-align: center;"><strong>Rs.<?php echo $total; ?></strong></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>

                                        <td style="text-align: center;"><strong>Delivery Charges</strong></td>
                                        <td style="text-align: center;"><strong>Rs.50</strong></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>

                                        <td style="text-align: center;"><strong>Total</strong></td>
                                        <td style="text-align: center;border-top: thin solid black;"><strong>Rs.<?php echo ($total + 50); ?></strong></td>
                                    </tr>
                                <?php else: ?>
                                    <tr>
                                        <td></td>
                                        <td></td>

                                        <td style="text-align: center;"><strong>SubTotal</strong></td>
                                        <td style="text-align: center;"><strong>Rs.<?php echo $total; ?></strong></td>
                                    </tr>
                                    <?php if ($order->__get("discount_price") != NULL): ?>
                                        <tr>
                                            <td></td>
                                            <td></td>

                                            <td style="text-align: center;"><strong>Discount</strong></td>
                                            <td style="text-align: center;"><strong>Rs.<?php echo $order->__get("discount_price"); ?></strong></td>
                                        </tr>
                                        <tr >
                                            <td></td>
                                            <td></td>

                                            <td style="text-align: center;"><strong>Total</strong></td>
                                            <td style="text-align: center; border-top: thin solid black;"><strong>Rs.<?php echo $order->__get("revised_price"); ?></strong></td>
                                        </tr>
                                    <?php else: ?>
                                        <tr>
                                            <td></td>
                                            <td></td>

                                            <td style="text-align: center;"><strong>Total</strong></td>
                                            <td style="text-align: center;border-top: thin solid black;"><strong>Rs.<?php echo $total; ?></strong></td>
                                        </tr>
                                    <?php endif; ?>

                                <?php endif; ?>

                            </table>
                        </div><br/>

                        <div class="foot">
                            <strong>Assuring you of our best service.<br/>
                                Warm Regards.<br/>
                                LaundryWala</strong>
                        </div>



                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>


    <style>
        td{
            padding: 7px 3px;

        }
    </style>
