<div class="mws-panel grid_8">
  <div id="mws-error-container">
    <p id="mws-error-message"></p>
  </div>
  <div class="mws-report-container clearfix"> 
    
    <!-- Statistic Item --> 
    <a class="mws-report " href="<?php echo $this->url(array("module"=>"admin","controller"=>"admins"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-user"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Admin</span> <span class="mws-report-value up">0</span> </span> 
    
    </a>
    
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"categories"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-sitemap-color"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Categories</span> <span class="mws-report-value up">0</span> </span> 
    </a> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"items"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-sport-tennis"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Items</span> <span class="mws-report-value up">0</span> </span> </a> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"delivery-type"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-travel"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Delivery Types</span> <span class="mws-report-value up">0</span> </span> </a> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"service-master"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-hammer"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Service Master</span> <span class="mws-report-value up">0</span> </span> </a> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"item-price"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-price-alert"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Item Price</span> <span class="mws-report-value up">0</span> </span> </a>
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"users"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-walk"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Users</span> <span class="mws-report-value up">0</span> </span> </a>
    
    <!-- Statistic Item --> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"orders"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-text-list-bullets"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Orders</span> <span class="mws-report-value up">0</span> </span> </a> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"orders","action"=>"summary"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-bookmark"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Order Summary</span> <span class="mws-report-value up">0</span> </span> </a> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"user-transaction"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-creditcards"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Transactions</span> <span class="mws-report-value up">0</span> </span> </a> 
    
    <a class="mws-report" href="<?php echo $this->url(array("module"=>"admin","controller"=>"coupons"),"default",true)?>"> 
    <!-- Statistic Icon (edit to change icon) --> 
    <span class="mws-report-icon mws-ic ic-photos"></span> 
    
    <!-- Statistic Content --> 
    <span class="mws-report-content"> <span class="mws-report-title">Coupons</span> <span class="mws-report-value up">0</span> </span> </a> </div>
  
  <!-- Panels End --> 
</div>
