

<div id="" class="forgot-box widget-box no-border visible">
    <div class="widget-body">
        <div class="widget-main">
            <h4 class="header red lighter bigger">
                <i class="icon-key"></i>
                Retrieve Password
            </h4>
            <?php if ($this->hasMessage): ?>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="alert alert-block alert-<?php echo $this->messageType ?> fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="fa fa-times"></i>
                            </button>
                            <?php if ($this->messageType == "danger"): ?>
                                <strong>Oh snap!</strong>
                            <?php elseif ($this->messageType == "success"): ?>
                                <strong>Well done!</strong>
                            <?php elseif ($this->messageType == "info"): ?>
                                <strong>Heads up!</strong>
                            <?php elseif ($this->messageType == "warning"): ?>
                                <strong>Warning!</strong>
                            <?php endif; ?>
                            <?php echo $this->message; ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <div class="space-6"></div>
            <p>
                Enter your email and to receive instructions
            </p>

            <form method="post">
                <fieldset>
                    <label>
                        <span class="block input-icon input-icon-right">
                            <input type="email" class="span12" placeholder="Email" name="admin_email"/>
                            <i class="icon-envelope"></i>
                        </span>
                    </label>

                    <div class="clearfix">
                        <button type="submit" class="width-35 pull-right btn btn-small btn-danger">
                            <i class="icon-lightbulb"></i>
                            Send Me!
                        </button>
                    </div>
                </fieldset>
            </form>
        </div><!--/widget-main-->

        <div class="toolbar center">
            <a href="<?php echo $this->baseUrl(); ?>/admin/auth/" class="back-to-login-link">
                Back to login
                <i class="icon-arrow-right"></i>
            </a>
        </div>
    </div><!--/widget-body-->
</div><!--/forgot-box-->