<div id="slider_wrapper2" style="margin-top:100px;">
    <div class="wrap">

        <h1>Payment</h1>

    </div>
</div>

<div class="clear"></div>

<div class="content" style="background: transparent">
    <?php if($this->flag == TRUE):?>
    <p style="font-size: 25px;text-align: center;"><strong>Payment Successful.Thank You for placing your order.Your Order has been recieved successfully.</strong></p>
    <?php else:?>
    <?php endif;?>

</div>


<div class="blue-bar">

</div>