<link href="<?php echo $this->baseUrl(); ?>/public/css/aboutus.css" rel="stylesheet">
<div class="container-fluid about-us-top">
    
</div>
<div class="container about-us-page">
    <div class="col-sm-12 ">
        <h1 class="text-center">About Us</h1>
        
        <p class="text-justify">Do you belong to the ambitious urban India? We're talking the endless traffic, constant stress, audacious goals and a busy lifestyle. As young working professionals, we were overwhelmed by demanding schedule and dire need to cut down on time we spent doing domestic chores. Laundry was one of them. Our market research pointed to various problems faced by customers with regards to hygiene, timing and service.That's when we set out to do something about it and then began the journey of Laundarywala - your one stop solution to all your laundry needs, in January 2015. We are based out of Noida and have ambitious plans to reach out across India.</p>
        <p class="text-justify">We pivot our focus on perfecting our services to ensure a superior customer experience.</p>

        <h3>What we do</h3>
        
        <p class="text-justify">We are proud pioneers of on-demand laundry services in India that includes washing, dry cleaning, steam ironing, quilt cleaning and other value added services to save you from laundry hassles.</p>
        <p class="text-justify">To ensure best customer experience, we provide a free pickup and delivery service to our users on their convenient time and location.</p>
        
        <h3>Why Choose Us</h3>
        
        <ul>
            <li>Technology: All the garments are processed through our unique 7-step cleaning technology at our central unit ensuring utmost care is taken when it comes to hygiene.</li>
            <li>Customer Experience: Our team not only consists of trained garment experts but also an on-the-toe logistics team that ensure best customer experience.</li>
            <li>Convenience: Your convenience is important to us. We provide pickup and delivery service to all our users free of cost. Moreover, you can choose your convenient date, time and location for pickup and delivery! Could it be more easier?</li>
            <li>Easy-to-use application and website interface: You are literally just a few taps away from checking off laundry from your to-do list!</li>
        </ul>
    </div>
</div>