<link href="<?php echo $this->baseUrl(); ?>/public/css/contactus.css" rel="stylesheet">
<div class="container-fluid text-center">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <h3>Contact Us</h3>
            <div class="row pad">
                <div class="col-sm-11 form-body">
                    <div class="form-group no-margin">
                        <input type="text" class="form-control margin" id="name" placeholder="Your Name">
                        <input type="text" class="form-control margin" id="email" placeholder="Email">
                        <div class="input-group margin">
                            <span class="input-group-addon">+91</span>
                            <input type="text" id="phone" name="phone" class="form-control" placeholder="Phone">
                        </div>
                        <select class="form-control margin" id="city">
                            <option>Select City</option>
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                        </select>
                        <select class="form-control margin" id="query">
                            <option>Query Type</option>
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                        </select>
                        <textarea class="form-control margin" rows="3" id="comment" placeholder="Add Your Comments"></textarea>
                        <div class="input-group-addon header-group-addon btn btn-success">SUBMIT</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3"></div>
    </div>
</div>