<div class="container-fluid" style=" color:white;">
    <div class="row blue-block-top" >
        <div class="col-sm-12" >
            <h1 class="text-center" style="margin:10px 0;padding:10px"><?php echo $this->headlineText; ?></h1>
            
            <?php /*?><div class="col-sm-2 user-block" style="" >
				<?php
                if (isset($this->userInfo)) {
                    ?>
                    
                    <?php
                }
                ?>
            </div><?php */?>
        </div>
        
    </div>
</div>