<?php
$thumb = $this->baseUrl() . "/public/thumbs/thumb.php";
$userInfo = array('userName' => $this->user_fname . ' ' . $this->user_lname, 'phone' => '7062232497', 'profileImage' => $this->user_img);
echo $this->partial('index/headerstrip.phtml', array('headlineText' => $this->headlineText, 'userInfo' => $userInfo));
$orderItems = new Application_Model_OrderItemsMapper();
?>
<div class="container" style="margin-top:60px;">
    <div class="row-fluid">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default panel-thead">
                <div class="panel-heading" role="tab">
                    <h4 class="">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                            <span class="col-md-3">Order Id</span>
                            <span class="col-md-3">Pickup Date</span>
                            <span class="col-md-3">Delivery Date</span>
                            <span class="col-md-3">Order Amount</span>
                        </a>
                    </h4>
                </div>
            </div>
            <?php
            foreach ($this->orders as $orderKey => $order) {
                ?>
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="heading<?php echo $order['order_id']; ?>">
                        <h4>
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $order['order_id']; ?>" aria-expanded="<?php echo $orderKey == 0 ? 'true' : 'false'; ?>" aria-controls="collapse<?php echo $order['order_id']; ?>">
                                <div class="col-md-3">
                                    <?php
                                    echo $order['order_id'];
                                    ?>
                                </div>
                                <div class="col-md-3">
                                    <?php
                                    echo $order['order_pickup'];
                                    ?>
                                </div>
                                <div class="col-md-3">
                                    <?php
                                    echo $order['order_delivery'];
                                    ?>
                                </div>
                                <div class="col-md-3">
                                    <?php
                                    echo $order['order_amount'];
                                    ?>
                                </div>

                            </a>
                        </h4>
                    </div>
                </div>
                <div id="collapse<?php echo $order['order_id']; ?>" class="panel-collapse collapse <?php echo $orderKey == 0 ? 'in' : ''; ?>" role="tabpanel" aria-labelledby="heading<?php echo $order['order_id']; ?>">
                    <div class="panel-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4">
                                    <h3>Address</h3>
                                    <?php
                                    $order_address = explode(",", $order['order_address']);
                                    foreach ($order_address as $address) {
                                        ?>
                                        <p><?php echo $address . ","; ?></p>
                                        <?php
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <h3>Telephone</h3>
                                    <p>
                                        <?php
                                        echo $this->user_number;
                                        ?>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <?php
                        if ($order['order_type'] == 'service') {
                            $orderItemList = $orderItems->getOrderItemByOrderId($order['order_id']);
                            if (count($orderItemList) && is_array($orderItemList)) {
                                ?>
                                <table class="responsive col-md-12 table-bordered">
                                    <thead>
                                        <tr>
                                            <td class="col-md-1">S.no</td>
                                            <td class="col-md-4"><?php echo $order['order_type'] == 'service' ? 'Service' : 'Package' ?></td>
                                            <td class="col-md-4">Item</td>
                                            <td class="col-md-4">Quantity</td>
                                            <td class="col-md-4">Price</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        if (count($orderItemList))
                                            foreach ($orderItemList as $_orderKey => $_order) {
                                                ?>
                                                <tr>
                                                    <td><?php echo $_orderKey + 1; ?></td>
                                                    <td><?php echo $_order->__get('order_service_name'); ?></td>
                                                    <td><?php echo $_order->__get('order_product_name'); ?> </td>
                                                    <td><?php echo $_order->__get('quantity'); ?> </td>
                                                    <td><?php echo $_order->__get('total_price'); ?> </td>
                                                </tr>
                                                <?php
                                            } else {
                                            foreach ($orders['order_services'] as $servicesKey => $services) {
                                                ?>
                                                <tr>
                                                    <td><?php echo $servicesKey + 1; ?></td>
                                                    <td><?php echo $services; ?></td>
                                                </tr>
                                                <?php
                                            }
                                        }
                                        ?>
                                        <tr>
                                            <td colspan="4" class="text-right">Delivery Charge: </td>
                                            <td><?php echo $order['delivery_charge']; ?></td>
                                        </tr>
                                        <tr>
                                            <td colspan="4" class="text-right">Discount: </td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td colspan="4" class="text-right">Service Tax</td>
                                            <td><?php echo $order['service_tax'] ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <?php
                            } else {
                                ?>
                                <table class="responsive col-md-12 table-bordered">
                                    <thead>
                                        <tr>
                                            <td class="col-md-1">S.no</td>
                                            <td class="col-md-4"><?php echo $order['order_type'] == 'service' ? 'Service' : 'Package' ?></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach ($order['order_services'] as $servicesKey => $services) {
                                                ?>
                                                <tr>
                                                    <td><?php echo $servicesKey + 1; ?></td>
                                                    <td><?php echo $services; ?></td>
                                                </tr>
                                                <?php
                                            }
                                            ?>
                                    </tbody>
                                </table>
                        <?php
                            }
                        } else {
                            ?>
                            <table class="responsive col-md-12 table-bordered">
                                <thead>
                                    <tr>
                                        <td class="col-md-1">S.no</td>
                                        <td class="col-md-4">Package</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td><?php echo $order['order_packages'][0]; ?></td>
                                    </tr>
                                </tbody>
                            </table>
                            <?php
                        }
                        ?>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>

    </div>
</div>