<div id="slider_wrapper2">
    <div class="wrap">

        <h1>Login to your account</h1>

    </div>
</div>
<?php if ($this->hasMessage): ?>
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-block alert-<?php echo $this->messageType ?> fade in">
                <button data-dismiss="alert" class="close close-sm" type="button">
                    <i class="fa fa-times"></i>
                </button>
                <?php if ($this->messageType == "danger"): ?>
                    <strong>Oh snap!</strong>
                <?php elseif ($this->messageType == "success"): ?>
                    <strong>Well done!</strong>
                <?php elseif ($this->messageType == "info"): ?>
                    <strong>Heads up!</strong>
                <?php elseif ($this->messageType == "warning"): ?>
                    <strong>Warning!</strong>
                <?php endif; ?>
                <?php echo $this->message; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<div class="clear"></div>

<div class="content" style="background:transparent">
    <div class="wrap" style="background: transparent; padding: 10px;">




        <div class="half-left">
            <h3>Reset Password</h3>

            <form id="contactform" method="post">
                <table>
                    <tr>
                        <td><input type="text" id="name" name="pass" placeholder="Enter New Password" /></td>
                    </tr>
                    <tr>
                        <td><input type="text" id="email" name="cpass" placeholder="Confirm Password" /></td>
                    </tr>
                    <tr>
                        <td>
                            <button type="submit" id="send" class="button">Change</button>
                        </td>
                       
                    </tr>
                </table>

            </form>

            <div class="clear"></div>
        </div>

        

        <div class="clear"></div>
        
    </div>
</div>

<div class="blue-bar">

</div>