<div class="row">
	<div class="col-sm-9 col-sm-offset-1">    	
        	<div class="row">
            	<div class="order-tracksummary-block">
                <div class="-tabhead col-sm-12">
                    <span>Order ID: 123123123</span>
                </div>
                <div class="-body col-sm-12">
                    <div class="row">
                    <div class="col-sm-6">PICKUP TIME : 09:00-10:00</div>
                    <div class="col-sm-6">DELIVERY TIME : 11:00-12:00</div>
                	</div>

                    <div class="row">
                                    
                        <div class="col-sm-12">
                            <ul>
                                <li>SERVICE : Laundry, Wash, DryClean, Ironing</li>
                                <li>PAYMENT : <span class="-pay-type">cash on delivery</span></li>                
                                <li>TO BE PAID : <span style="color:#34B3E2">RS. 799</span></li>            
                            </ul>
                        </div>
                        
                    </div>
                    <div class="row">
                    <div class="col-sm-12">
                    	<ul class="track-flow-dia">
                        	<li class="track-process">IN PROCESS</li>
                            <li class="track-pickup">PICKUP DONE</li>
                            <li class="track-delivered">DELIVERY DONE</li>
                        </ul>                    	
                    </div>
                    </div>                                        
                </div>
                </div>
                
                
                <div class="order-tracksummary-block">
                <div class="-tabhead col-sm-12">
                    <span>Order ID: 123123123</span>
                </div>
                <div class="-body col-sm-12">
                    <div class="row">
                    <div class="col-sm-6">PICKUP TIME : 09:00-10:00</div>
                    <div class="col-sm-6">DELIVERY TIME : 11:00-12:00</div>
                	</div>

                    <div class="row">
                                    
                        <div class="col-sm-12">
                            <ul>
                                <li>SERVICE : Laundry, Wash, DryClean, Ironing</li>
                                <li>PAYMENT : <span class="-pay-type">cash on delivery</span></li>                
                                <li>TO BE PAID : <span style="color:#34B3E2">RS. 799</span></li>            
                            </ul>
                        </div>
                        
                    </div>
                    <div class="row">
                    <div class="col-sm-12">
                    	<ul class="track-flow-dia">
                        	<li class="track-process">IN PROCESS</li>
                            <li class="track-pickup">PICKUP DONE</li>
                            <li class="track-delivered">DELIVERY DONE</li>
                        </ul>                    	
                    </div>
                    </div>                                        
                </div>
                </div>
                
                <div class="order-tracksummary-block">
                <div class="-tabhead col-sm-12">
                    <span>Order ID: 123123123</span>
                </div>
                <div class="-body col-sm-12">
                    <div class="row">
                    <div class="col-sm-6">PICKUP TIME : 09:00-10:00</div>
                    <div class="col-sm-6">DELIVERY TIME : 11:00-12:00</div>
                	</div>

                    <div class="row">
                                    
                        <div class="col-sm-12">
                            <ul>
                                <li>SERVICE : Laundry, Wash, DryClean, Ironing</li>
                                <li>PAYMENT : <span class="-pay-type">cash on delivery</span></li>                
                                <li>TO BE PAID : <span style="color:#34B3E2">RS. 799</span></li>            
                            </ul>
                        </div>
                        
                    </div>
                    <div class="row">
                    <div class="col-sm-12">
                    	<ul class="track-flow-dia">
                        	<li class="track-process">IN PROCESS</li>
                            <li class="track-pickup">PICKUP DONE</li>
                            <li class="track-delivered">DELIVERY DONE</li>
                        </ul>                    	
                    </div>
                    </div>                                        
                </div>
                </div>
            </div>
    	
	</div>
</div>


<script type="text/javascript">
$(document).ready(function(e){
	
    $(".-tabhead").click(function(){
		var par = $(this).parents(".order-tracksummary-block");
		$(par).toggleClass("active");
		
		$(par).find(".-body").slideToggle("100");
	})
	
	$(".order-tracksummary-block:first").find(".-tabhead").click();

});
</script>