
<div class="row">
<div class="subscription-pack-block">
	<div class="col-sm-10 col-sm-offset-1">
    	<div class="row">
        	<div class="col-sm-6"><span class="-title">Single:999</span></div>
            <div class="col-sm-6 text-right"><a class="btn btn-info">Schedule now</a></div>
        </div>
        <div class="row">
        	<div class="col-sm-12">
            	<table>
                  <tr>
                    <td>Date Of purchase</td>
                    <td width="25px" class="text-center">:</td>
                    <td>11th November 2015</td>
                  </tr>
                  <tr>
                    <td>Ending On</td>
                    <td>:</td>
                    <td>11th November 2015</td>
                  </tr>
                  <tr>
                    <td>Number of clothes left</td>
                    <td>:</td>
                    <td>50</td>
                  </tr>
                  <tr>
                    <td>Number of pickups left</td>
                    <td>:</td>
                    <td>50</td>
                  </tr>
                </table>

            </div>
            
        </div>
        
        
        
        
    </div>
</div>
</div>