<?php 
        $baseUrl     = Zend_Controller_Front::getInstance()->getBaseUrl();
		$imagepath   = Zend_Registry::getInstance()->constants->profile_image;
		$thumb       = $baseUrl."/public/thumbs/thumb.php";	
		$namespace   = new Zend_Session_Namespace('someaction');
		$model       =  new Users_Model_User();
		$users       = $namespace->data;
		$userid      = $users['userid'];
		$email       = $users['email'];
		$friends     = $model->getyourfriends($userid);
        if(empty($friends))
           $friends  = $userid;
        else
	       $friends  = $friends.','.$userid;
		   
		   $query_actual_result = $model->fetchlatest_actual_result($friends);		   
		   $actual_row_count    = count($query_actual_result);
?>
<!--<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/ckeditor/ckeditor.js"></script>-->
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/nicEdit.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/ckeditor/sample.css" />
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/script.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/css/main.css" />
<script src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/jquery.nanoscroller.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/ajaxjs/album.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/css/liveurl.css" />
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/jqgrid/ajaxupload.3.5.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/ajaxjs/multiajax.js"></script>
<style>
         
	    #more{
		background: none repeat scroll 0 0 #EEEEEE;
    border: 1px solid #CFCFCF;
    color: #000000;
    display: none;
    font-weight: bold;
    left: 605px;
    padding: 5px;
    position: fixed;
    top: 400px;
	z-index:99;

	    }
	    #no-more{
		background: none repeat scroll 0 0 #EEEEEE;
    border: 1px solid #CFCFCF;
    color: #000000;
    display: none;
    font-weight: bold;
    left: 605px;
    padding: 5px;
    position: fixed;
    top: 400px;
	z-index:99;

	    }
	    #result{
		
	    }
        </style>
<script type="text/javascript">
            var page = 1;

            $(window).scroll(function () {
                $('#more').hide();
                //$('#no-more').hide();

                if($(window).scrollTop() + $(window).height() > $(document).height() - 200) {
                    $('#more').css("top","400");
                    $('#more').show();
                }
                if($(window).scrollTop() + $(window).height() == $(document).height()) {

                    $('#more').hide();
                    //$('#no-more').hide();

                    page++;

                    var data = {
                        page_num: page
                    };

                    var actual_count = "<?php echo $actual_row_count; ?>";

                    if((page-1)* 15 > actual_count){
                        $('#no-more').css("top","400");
                        //$('#no-more').show();
                    }else{
                        $.ajax({
                            type: "POST",
                            url: "<?php echo $baseUrl; ?>/users/pagging/index",
                            data:data,
                            success: function(res) {
                                $("#result").append(res);
                                console.log(res);
                            }
                        });
                    }

                }


            });

        </script>
   <!--Left Menu Section Start-->
   <script>
   
   function CountLikeComent(post_id,type,evt)
{
	var  ajxlikeid = '.comentlike'+post_id;
	
 $.ajax({
			type: "GET",
			url: "<?php echo $baseUrl; ?>/users/index/comentlike",
			data: "post_id="+ post_id+'&type='+type, 
			cache: true,
			success: function(data){
					
			$(ajxlikeid).html(data);		
		}
	});			
}
   
$(document).ready(function() {
$('#add-job').validate({
    ignore: [],         
    rules: {
                articlebody: {
                    required: function() 
                    {
                    CKEDITOR.instances.articlebody.updateElement();
                    }
                    }
                },
                messages: {                
                articlebody: "Required"
                },
                /* use below section if required to place the error*/
                errorPlacement: function(error, element) 
                {
                    if (element.attr("name") == "articlebody") 
                   {
                    error.insertBefore("textarea#articlebody");
                    } else {
                    error.insertBefore(element);
                    }
                }
            });
});
</script>
 <script language="javascript" type="text/javascript">
function ShowHide(cid)
{
        var comid="com-"+cid;
		el = document.getElementById(comid); 
    	 if (el.style.display == "none")
        { 
            el.style.display = "block"; 
        } 
     else 
        { 
            el.style.display = "none"; 
        } 

}


function cmd_del()
{
var x=confirm("Do You want to delete this records");
if(x)
return true;
else 
return false;

}

</script>
<script type="text/javascript">

function LikeChange(post_id,type,evt)
{
	var  ajxlikeid = '.ajxlikeid'+post_id;
	
 $.ajax({
			type: "GET",
			url: "<?php echo $baseUrl; ?>/users/profile/like",
			data: "post_id="+ post_id+'&type='+type, 
			cache: true,
			success: function(data){
					
			$(ajxlikeid).html(data);		
		}
	});			
}

function DislikeChange(post_id,type,evt)
{ 
 
 var  ajxdislikeid = '#ajxdislikeid'+post_id;

 $.ajax({
			type: "GET",
			url: "<?php echo $baseUrl; ?>/users/profile/dislike",
			data: "post_id="+ post_id+'&type='+type, 
			cache: true,
			success: function(data){	
			
			$(ajxdislikeid).html(data);		
		}
	});			
}


function LikePostVoteClose(did)
{
var voteid = document.getElementById(did);
voteid.style.display = "none";  

}



// get xy mouse pointer
function getXY(e) {
	var posx = 0;
	var posy = 0;
	if (!e) var e = window.event;
	if (e.pageX || e.pageY) 	{
		posx = e.pageX;
		posy = e.pageY;
	}
	else if (e.clientX || e.clientY) 	{
		posx = e.clientX + document.body.scrollLeft
			+ document.documentElement.scrollLeft;
		posy = e.clientY + document.body.scrollTop
			+ document.documentElement.scrollTop;
	}
	return new Array(posx,posy);
//	alert(posx+"\n"+posy);
	// posx and posy contain the mouse position relative to the document
	// Do something with this information
}
function LikeAlbumChange(post_id,type,evt)
{
	var  ajxlikeid = '.ajxlikeid'+post_id;
 $.ajax({
			type: "GET",
			url: "<?php echo $baseUrl; ?>/users/profile/albumlike",
			data: "post_id="+ post_id+'&type='+type, 
			cache: true,
			success: function(data){
					
			$(ajxlikeid).html(data);		
		}
	});			
}

function LikemultimgChange(post_id,type,evt,imgp)
{
	var  ajxlikeid = '.ajxlikeid'+post_id;
 $.ajax({
			type: "GET",
			url: "<?php echo $baseUrl; ?>/users/ajax/multimglike",
			data: "post_id="+ post_id+"&type="+type+"&img_t="+imgp, 
			cache: true,
			success: function(data){
					
			$(ajxlikeid).html(data);		
		}
	});			
}

function ShowLikeUser(post_id,type,evt)
{  
  
  var dialogvoteid="ShowLikeUser"+post_id;
   $(".uesershow").html('loading...');
//var voteid = document.getElementById("dialogvote");
//voteid.style.display = "block";
$.ajax({
			type: "POST",
			url: "<?php echo $baseUrl; ?>/users/profile/likeusers",
			data: "post_id="+ post_id+'&type='+type, 
			cache: true,
			success: function(data){
								
			$(".uesershow").html(data);		
		}
	});	
}


function ShowUnLikeUser(post_id,type,evt)
{  
  
  var dialogvoteid="ShowUnLikeUser"+post_id;
  
  $(".ueserunlike").html('loading...');
  
 $.ajax({
			type: "POST",
			url: "<?php echo $baseUrl; ?>/users/profile/unlikeusers",
			data: "post_id="+ post_id+'&type='+type, 
			cache: true,
			success: function(data){
								
			$(".ueserunlike").html(data);		
		}
	});	
}

function ShowUnLikeUserClose(did)
{
var voteid = document.getElementById(did);
voteid.style.display = "none";  

}

function EditUserComment(post_id,share_id)
{ 

  var  editcomment = '.editcomment'+post_id;
   $(editcomment).html('loading...');
  
 $.ajax({
			type: "POST",
			url: "<?php echo $baseUrl; ?>/users/profile/editusercomment",
			data: "post_id="+ post_id+"&share_id="+share_id+"&type=homepage", 
			cache: false,
			success: function(data){
								
			$(editcomment).html(data);
			$( 'p' ).remove();		
		}
	});	
}
</script>
<style>
.divstyle{
	position:absolute;
	left:overflow:auto;
	border:#666666 solid 10px;
	background-color:#ebf8ff;
	padding:8px;
}
</style>
<script>
function getXY(e) {
	var posx = 0;
	var posy = 0;
	if (!e) var e = window.event;
	if (e.pageX || e.pageY) 	{
		posx = e.pageX;
		posy = e.pageY;
	}
	else if (e.clientX || e.clientY) 	{
		posx = e.clientX + document.body.scrollLeft
			+ document.documentElement.scrollLeft;
		posy = e.clientY + document.body.scrollTop
			+ document.documentElement.scrollTop;
	}
	return new Array(posx,posy);
//	alert(posx+"\n"+posy);
	// posx and posy contain the mouse position relative to the document
	// Do something with this information
}

function SHSDivWithPos(did,act,evt){
	//alert("kjljl");
	var divObject=document.getElementById(did);
	//alert(divObject);
	var xyPOS=getXY(evt);
	divObject.style.display=act;
	divObject.style.left=xyPOS[0]+"px";
	divObject.style.top=xyPOS[1]+"px";
}

function SHSDiv(did,act){
	if(document.getElementById(did)){
		var sdivObject=document.getElementById(did);
		sdivObject.style.display=act;
	}
}

function ShowHomeShare(type)
{  
  
  $("#homedata").html('loading...');
  
 $.ajax({
			type: "POST",
			url: "<?php echo $baseUrl; ?>/users/index/homepagedata",
			data: "com_type="+ type, 
			cache: true,
			success: function(data){
								
			$("#homedata").html(data);		
		}
	});	
}

function textareeditor(valu)
{
 var str = $("#articlebody").val();
  var text = document.getElementById("articlebody");
  var selecttxt = text.value.substr(text.selectionStart,text.selectionEnd-text.selectionStart);
  alert(selecttxt);
 
  if(valu == 'bold'){  
  var bd =  selecttxt.bold();alert(bd)
  document.getElementById("articlebody").innerHTML = bd;
  $("#articlebody").val(bd);
  }
}
function addArea2() {
    
     var str = $("#articlebody").val();
     if(str!=''){
	area2 = new nicEditor({fullPanel : true}).panelInstance('articlebody');
    }
}
function removeArea2() {
	area2.removeInstance('articlebody');
}

//bkLib.onDomLoaded(function() { toggleArea1(); });

</script>
<!--<script src="http://code.jquery.com/jquery-1.8.3.min.js" type="text/javascript"></script>-->
<script>
$(document).ready(function() {
   $( ".newclass" ).live( "keyup", function() {
      var txts = $(this).text();
      if(txts =='')
      {
        area2.removeInstance('articlebody'); 
        $("#articlebody").val('');
      }  
      
});
    });
    

</script>
   
   <!--Left Menu Section End-->
   
   <div id="sucess-msg_index"> <?php  echo $this->flashMessages();?></div>
   <!--Post Center Section Start-->
    <div class="post-center-wrapper">
        <form name="cmntform" id="add-job" action="" method="post" onsubmit="return validateForm()" enctype="multipart/form-data">
     <input type="hidden" name="share" id="share" />
             <?php
			  if(@$_REQUEST['mem_id']==$userid)
			  {			  
			  ?>
			 
			   <input type="hidden" name="lock" value="2" />
			     <?php } else { ?>
			   <input type="hidden" name="lock" value="3" />
			   
			   <?php } ?>
     <div class="top-part">
      <div class="editor-post" id="editor-post">
        <div class="wrap" id="homedata">      
         <textarea name="articlebody" id="articlebody" onkeyup="addArea2();" placeholder="Share Your Slice..."></textarea>
        </div>

            <div class="liveurl-loader"></div>        
              <div class="liveurl">
                  <div class="close" title="Entfernen"></div>
                  <div class="inner">
                      <div class="image"> </div>
                      <input type="hidden" name="liveimage" id="liveimage" value="">
                      <div class="details">
                          <div class="info">
                              <div class="title"> </div>
                              <input type="hidden" name="livetitle" id="livetitle" value="">
                              <div class="description"> </div> 
                              <input type="hidden" name="livedescrip" id="livedescrip" value="">
                              <div class="url"> </div>
                              <input type="hidden" name="liveUrl" id="liveUrl" value="">
                          </div>

                          <div class="thumbnail">
                              <div class="pictures">
                                  <div class="controls">
                                      <div class="prev button inactive"></div>
                                      <div class="next button inactive"></div>
                                      <div class="count">
                                          <span class="current">0</span><span> von </span><span class="max">0</span>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div class="video"></div>
                            <input type="hidden" name="livevideo" id="livevideo" value="">
                      </div>
                  </div>
              </div>
      </div>
        <div id ="fileupd" class="editor-post" style="display:none;"> 
            <div class="wrap" id="homedata">      
               <div id="mainbody">		
                    <div id="upload">Upload <span id="chng_file">File</span></div><span id="status"></span>
                                <div class="clearall"></div>
		<ul id="files" ></ul>
                </div> 
                
<!--              <div><input type="file" name="slicedata" id="slicedata"></div>-->
                <div><p><input type="text" class="cmn-input title-input" name="description" id="descr" placeholder="Title"></p></div>
              <input type="hidden" name="up_type" id="up_type" value="">
              <input type="hidden" name="up_vedio" id="up_vedio" value="">
              <input type="hidden" name="up_vedio_type" id="up_vedio_type" value="">
<!--              <input type="hidden" name="file_names[]" id="file_names" value="">-->
           </div>
      </div>   
      <div class="clear"></div>
      <div class="edit-icons">
       <a href="javascript:void(0)" id=""><div class="slice-pices"></div></a>
       <a href="javascript:void(0)" id=""><div class="user-ad"></div></a>
       <a href="javascript:void(0)" id=""><div class="place"></div></a>
       <a href="javascript:void(0)" id=""><div class="articles2"></div></a>
       <div class="grey-bdr">
       <a href="javascript:void(0)" id=""><div class="sticker"></div></a>
       <a href="javascript:void(0)" id=""><div class="smily"></div></a>
       <a href="javascript:void(0)" id="video" ><div class="video"></div></a>
       <a href="javascript:void(0)" id="gif"  ><div class="gif"></div></a>
       <a href="javascript:void(0)" id="photo"><div class="photo"></div></a>
       </div>
       <div class="btn-wrap"><input type="submit" value="Slice it"></div>
      </div>
     </div>
     </form>
     <!--Live Slice post part start-->
     <div id='more'>Loading .....</div>
    
      <div id='result' class="live-slice-wrapper">
      <?php 
            echo $this->data_share_result;
       ?>	
 </div>
     <!--Live Slice post part end-->
     
    </div>
   
   <div id="photo_preview" style="display:none">
        <div class="photo_wrp">
            
            <div style="clear:both"></div>
            
            <div class="v-gal-lft-div">
            <div class="pleft">test1
            
            </div>
            </div>
            
            <div class="v-gal-rght-div">
            <div class="close-bnt-rp"><img class="close" src="<?php echo $baseUrl; ?>/public/images/Icon_Close.png" /></div>
            <div class="v-gal-cmt-div">
            <div class="pright">
          	</div>
            </div>
          </div>
            <div style="clear:both"></div>
        </div>
    </div>
   <!--Post Center Section End-->
   
   <!--Right Box Start-->
   
   <!--Right Box End--> 
   <script type="text/javascript">
    $(document).ready(function(){
        $('.removwe').live('click',function(){
        $(this).parent('li').remove();
         $("#upload").show();
        });
        $('.grey-bdr a').click(function(){
            if($(this).attr('id')!='')
            {
                 var flag = $(this).attr('id');
                  $("#editor-post").hide();
                  $("#fileupd").show();
                  $("#up_type").val(flag);
                  $("#chng_file").html(flag);
            }else{
                
                $("#editor-post").show();
                  $("#fileupd").hide(); 
            }
              $('#files li').remove();
             $("#upload").show();
        });
    });
  

   
    function validateForm()
    {
       var typs = $("#up_type").val(); 
       if(typs == ''){
            var x=document.forms["cmntform"]["articlebody"].value;
            if (x==null || x=="")
            {
                alert("Please Fill the Text");
                return false;
            }
      }else{
            $('.success-img').each(function(){
                var elm =$(this).find("img").attr("id");           
                $('#add-job').append('<input type="hidden" name="file_names[]" value="'+elm+'">');
            });
        }
    }  
   </script>    
  
 <script type="text/javascript" >
   $(function(){
       var btnUpload = $('#upload');
       var status    = $('#status');
       var urls      = "<?php echo $baseUrl;?>/users/index/savesliceimage";
       var imgpath   = "<?php echo $baseUrl?>/docs/temp_image/";
       new AjaxUpload(btnUpload, {
             action: urls,
             name: 'uploadfile',
	     onSubmit: function(file, ext){
                 var img_type =  $("#up_type").val();
                 if(img_type == 'gif')
                 {
                       if (!(ext && /^(gif|gif)$/.test(ext))){                           
			   status.text('Only GIF files are allowed here');// extension is not allowed
			   return false;
                        }
                 }else if(img_type == 'photo'){
		if (!(ext && /^(jpg|png|jpeg|gif)$/.test(ext))){                           
			status.text('Only JPG, PNG or GIF files are allowed');// extension is not allowed
			   return false;
		   }
               }else{
                   if (!(ext && /^(mp4|webm|ogg)$/.test(ext))){                           
			status.text('Only mp4,webm and ogg files are allowed');// extension is not allowed
			   return false;
		   }
               }
               
		          status.text('Uploading...');
		     },
		  onComplete: function(file, response){
				//On completion clear the status
				status.text('');
				//Add uploaded file to list
                                var datass   = response.split("#");
                                var fil_type = datass[1];
				if(datass[0]==="success")
                                {
                                        if(fil_type == "video")
                                        {     
                                            $("#upload").hide();
                                              $("#up_vedio").val(file);
                                                $("#up_vedio_type").val(datass[2]);
                                               $('<li></li>').appendTo('#files').html('<video width="430" height="230" controls><source src="'+imgpath+file+'" id="'+file+'" type="'+datass[2]+'"> </video><a href="javascript:void(0);"  class="removwe"></a>').addClass('success-img vidsa');   
                                        }else{
                                               $('<li></li>').appendTo('#files').html('<img src="'+imgpath+file+'"  alt="" id="'+file+'"/><a href="javascript:void(0);"  class="removwe"></a>').addClass('success-img');
                                            }
                                  }else{
				      $('<li></li>').appendTo('#files').text(file).addClass('error-img');
				    }
			   }
		   });
		
	});
</script>
   
  <script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/jquery.liveurl.js"></script>
   <script type="text/javascript"> 
     var curImages = new Array();               
      $('textarea').liveUrl({
       loadStart : function(){
            $('.liveurl-loader').show();
         },
        loadEnd : function(){
            $('.liveurl-loader').hide();
        },
        success : function(data) 
        {                        
            var output = $('.liveurl');
            output.find('.title').text(data.title);
                               $("#livetitle").val(data.title);
            output.find('.description').text(data.description);
                               $("#livedescrip").val(data.description);
            output.find('.url').text(data.url);
                               $("#liveUrl").val(data.url);
            output.find('.image').empty();
                           
            output.find('.close').one('click', function() 
            {
                var liveUrl     = $(this).parent();
                liveUrl.hide('fast');
                liveUrl.find('.video').html('').hide();
                liveUrl.find('.image').html('');
                liveUrl.find('.controls .prev').addClass('inactive');
                liveUrl.find('.controls .next').addClass('inactive');
                liveUrl.find('.thumbnail').hide();
                liveUrl.find('.image').hide();

                $('textarea').trigger('clear'); 
                curImages = new Array();
            });

            output.show('fast');

            if (data.video != null) {                       
                var ratioW        = data.video.width  /350;
                data.video.width  = 350;
                data.video.height = data.video.height / ratioW;

                var video = 
                '<object width="' + data.video.width  + '" height="' + data.video.height  + '">' +
                    '<param name="movie"' +
                          'value="' + data.video.file  + '"></param>' +
                    '<param name="allowScriptAccess" value="always"></param>' +
                    '<embed src="' + data.video.file  + '"' +
                          'type="application/x-shockwave-flash"' +
                          'allowscriptaccess="always"' +
                          'width="' + data.video.width  + '" height="' + data.video.height  + '"></embed>' +
                '</object>';
                output.find('.video').html(video).show();
                 $("#livevideo").val(data.video.file);

            }
        },
        addImage : function(image)
        {   
            var output  = $('.liveurl');
            var jqImage = $(image);
            jqImage.attr('alt', 'Preview');

            if ((image.width / image.height)  > 7 
            ||  (image.height / image.width)  > 4 ) {
                // we dont want extra large images...
                return false;
            } 

            curImages.push(jqImage.attr('src'));
            output.find('.image').append(jqImage);
                 $("#liveimage").val(jqImage.attr('src')); 

            if (curImages.length == 1) {
                // first image...

                output.find('.thumbnail .current').text('1');
                output.find('.thumbnail').show();
                output.find('.image').show();
                jqImage.addClass('active');

            }

            if (curImages.length == 2) {
                output.find('.controls .next').removeClass('inactive');
            }

            output.find('.thumbnail .max').text(curImages.length);
        }
    });
 
    $('.liveurl ').on('click', '.controls .button', function() 
    {
        var self        = $(this);
        var liveUrl     = $(this).parents('.liveurl');
        var content     = liveUrl.find('.image');
        var images      = $('img', content);
        var activeImage = $('img.active', content);

        if (self.hasClass('next')) 
             var elem = activeImage.next("img");
        else var elem = activeImage.prev("img");

        if (elem.length > 0) {
            activeImage.removeClass('active');
            elem.addClass('active');  
            liveUrl.find('.thumbnail .current').text(elem.index() +1);

            if (elem.index() +1 == images.length || elem.index()+1 == 1) {
                self.addClass('inactive');
            }
        }

        if (self.hasClass('next')) 
             var other = elem.prev("img");
        else var other = elem.next("img");

        if (other.length > 0) {
            if (self.hasClass('next')) 
                   self.prev().removeClass('inactive');
            else   self.next().removeClass('inactive');
       } else {
            if (self.hasClass('next')) 
                   self.prev().addClass('inactive');
            else   self.next().addClass('inactive');
       }

    });
</script>
 
