<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<!-- Apple iOS and Android stuff (do not remove) -->
<meta name="apple-mobile-web-app-capable" content="no" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />

<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,maximum-scale=1" />

<!-- Required Stylesheets -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/reset.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/text.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/fonts/ptsans/stylesheet.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/core/form.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/core/login.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/core/button.css" media="screen" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/mws.theme.css" media="screen" />

<!-- JavaScript Plugins -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/js_new/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/js_new/jquery.placeholder.js"></script>

<!-- jQuery-UI Dependent Scripts -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/jui/js/jquery-ui-effects.min.js"></script>

<!-- Plugin Scripts -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/plugins/validate/jquery.validate-min.js"></script>

<!-- Login Script -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/js_new/core/login.js"></script>

<title>Laundrywala - Login Page</title>

</head>

<body>
    
    <div id="mws-login-wrapper">
        <div id="mws-login">
            <h1>Login</h1>
            <div class="mws-login-lock"><img src="<?php echo $this->baseUrl(); ?>/public/admin_assets/assets/css_new/icons/24/locked-2.png" alt="" /></div>
            <?php echo $this->layout()->content; ?>
            </div>
    </div>

</body>
</html>