<footer class='clearfix'>
    <div class="container">
        <div class="row footer-part-1">
            <div class="col-md-7 about-us-text text-justify" style="padding-right:70px;">
                <h2 class="footer-title">About Us</h2>
                <p>Do you belong to the ambitious urban India? We're talking the endless traffic, constant stress, audacious goals and a busy lifestyle. As young working professionals, we were overwhelmed by demanding schedule and dire need to cut down on time we spent doing domestic chores. Laundry was one of them. Our market research pointed to various problems faced by customers with regards to hygiene, timing and service.That's when we set out to do something about it and then began the journey of Laundarywala - your one stop solution to all your laundry needs, in January 2015. We are based out of Noida and have ambitious plans to reach out across India.</p>
            </div>
            <div class="col-md-2">
                <h2 class="footer-title">Services</h2>
                <ul class="services-list">
                	<li>Dry Clean</li>
                    <li>Steam Press</li>
                    <li>Laundry</li>
                    <li>Wash & Fold</li>
                    <li>Starching</li>
                    <li>Leather Cleaning</li>
                    <li>Leather Polishing</li>
                    <li>Ladies Bag</li>
                    <li>Fabric Softner</li>
                    <li>Fabric Conditioner</li>
                    <li>Shoe Servicing</li>
                </ul>
            </div>
            <div class="col-md-3">
                <h2 class="footer-title">Contact</h2>
                <ul class="services-list">
                    <li>
                        <i class="fa fa-mobile"></i>
                        <span>&nbsp;+91-9953180071</span>
                    </li>
                    <li>
                        <i class="fa fa-envelope"></i>
                        <span>info@laundrywala.co.in</span>
                    </li>
                    <li>
                        <i class="fa fa-clock-o"></i>
                        <span>Operating Hours - 8 AM - 10 PM</span>
                    </li>
                    <li>
                        <i class="fa fa-clock-o"></i>
                        <span>Calling Hours - 8 AM - 10 PM</span>
                    </li>
                </ul>
            </div>
<!--            <div class="col-md-2">
                <h2>Office</h2>
                <p>A-109Q,<br>Second Floor,<br>Sector-80,<br>Noida-201305</p>
            </div>-->
        </div>
    </div>
    <div class="container-fluid footer-part-2">
        <div class="container">
            <div class="row">
                <ul class='footer-links'>
<!--                    <li><a href='<?php echo $this->baseUrl(); ?>/index/aboutus'>ABOUT US</a></li>
                    <li><a href='<?php echo $this->baseUrl(); ?>/index/contactus'>CONTACT US</a></li>-->
                    <li>
                        <a target="_blank" href='https://www.facebook.com/LaundryWala'>
                            <img src="<?php echo $this->baseUrl(); ?>/public/img/facebook-footer-icon.png">
                        </a>
                    </li>
                    <li>
                        <a target="_blank" href='https://twitter.com/LaundryWala/'>
                            <img src="<?php echo $this->baseUrl(); ?>/public/img/twitter-footer-icon.png">
                        </a>
                    </li>
                    <li>
                        <a target="_blank" href='https://www.linkedin.com/company/laundrywala'>
                            <img src="<?php echo $this->baseUrl(); ?>/public/img/linkedin-footer-icon.png">
                        </a>
                    </li>
                </ul>
                <p class='copyright-text text-center'>
                    © 2015 Urban Consumer Solutions Pvt Ltd. All rights reserved
                </p>
            </div>
        </div>
    </div>
</footer>