<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">	
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Home_Page</title>

    <!-- Bootstrap -->
    <link href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl(); ?>/public/css/body_forced-2.css" rel="stylesheet">
  <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery-1.11.3.min.js"></script>
  </head>
  <body>
	<nav class="navbar navbar-default navbar-fixed-top" style="">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/public/img/lw_logo_trans.png" ></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="nav_li"><a href="#">Price List</a></li>
            <li class="nav_li"><a href="#">FAQ's</a></li>
            <li class="nav_li"><a href="#">BLOG</a></li>
			<li><a href="#"><img src="<?php echo $this->baseUrl(); ?>/public/img/play_logo_trans.png" class="img-responsive" style="width:70%;"></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
