<?php
$myControllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$myActionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?><!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <title>Laundrywala | On demand laundry and dry clean service</title> <!-- Title of the page -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/public/img/favicon.ico" type="image/x-icon">
        <link rel="icon" href="<?php echo $this->baseUrl(); ?>/public/img/favicon.ico" type="image/x-icon">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->baseUrl(); ?>/public/css/body_forced.css" rel="stylesheet" media="screen">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"/>
        <link href="<?php echo $this->baseUrl(); ?>/public/css/body_forced.css" rel="stylesheet" media="screen">
        <!--<link href="<?php echo $this->baseUrl(); ?>/public/css/body_forced-2.css" rel="stylesheet" media="screen">-->
        <link href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.css" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl(); ?>/public/css/style.css" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl(); ?>/public/css/stylenew.css" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl(); ?>/public/js/awesomplete/awesomplete.css" rel="stylesheet" media="screen">
        <script src="<?php echo $this->baseUrl(); ?>/public/js/jquery-1.11.3.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/js/bootstrap.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/js/init.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/js/general.js?v=<?php echo strtotime(date('Y-m-d H:i:s'))?>"></script>
        <script src="<?php echo $this->baseUrl(); ?>/public/js/awesomplete/awesomplete.js"></script>
        <script type="text/javascript">
            var baseUrl = '<?php echo $this->baseUrl(); ?>';
            </script>
    </head>
    <body>
        <?php print $this->render('header.phtml'); ?>
        <div class="login-main-wrapper">
            <?php echo $this->layout()->content; ?>
        </div>
        <?php 
        if(!(isset($this->noFooter) && $this->noFooter)){
            print $this->render('footer.phtml'); 
		}
        ?>
    </body>
</html>