<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-speech-bubble-2"> Update Coupon </span>
    </div>
    <div class="mws-panel-body">
        <form class="mws-form" method="post" enctype="multipart/form-data">
        	<?php if ($this->hasMessage): ?>
                <div class="mws-form-message <?php echo $this->messageType == 'danger' ? 'error' : $this->messageType; ?> fade in">
                    <?php if ($this->messageType == "danger"): ?>
                        <strong>Oh snap!</strong>
                    <?php elseif ($this->messageType == "success"): ?>
                        <strong>Well done!</strong>
                    <?php elseif ($this->messageType == "info"): ?>
                        <strong>Heads up!</strong>
                    <?php elseif ($this->messageType == "warning"): ?>
                        <strong>Warning!</strong>
                    <?php endif; ?>
                    <?php echo $this->message; ?>
                </div>
            <?php endif;?>
            <?php
                $elements = $this->form->getElements();
				
                foreach ($elements as $element):
                    ?>
                <div class="mws-form-inline"><div class="mws-form-row"><?php echo $element; ?></div></div>    
                    
                    <?php
                endforeach;
                ?>
			
            <div class="mws-button-row">
                    <input type="hidden" name="request_type" value="edit">
                    <button type="submit" class="mws-button red" >Update</button>
                </div>	
            
        </form>
    </div>
</section>

<script type="text/javascript">
$(".mws-datepicker").datepicker({
	showOtherMonths:true,
	minDate: '0',
	dateFormat:"yy-mm-dd"
});

  $(".mws-form").validate({
	  
	  rules:{
		  coupon_type:{
			  	required:true,
		  },
		  coupon_code:{
			  	required:true,
			  	minlength:4,
				maxlength:10,				
		  },
		  coupon_value:{
			  	number:true,
			  	required:true,			  	
				min:1,
				
				max:{
					param: 99,
					depends: function(element) {
					  return $("#coupon_type").val()=="percentage";
					}
				},
		  },
		  coupon_last_date:{			  	
			  	required:true,			  					
		  },
		  coupon_occourence:{
			  	digits:true,
			  	required:true,			  	
				min:1,
				max:100,
		  },
		  coupon_min_billing:{
			  	digits:true,
				min:1,
				max:100000,
		  },
		  coupon_max_discount:{
			  	digits:true,			  	
				min:1,
				max:100000,
		  },
		  
		  
	  },
	  messages:{
		  coupon_type:"Please select coupon type",
		  coupon_code:{
			  	required:"Enter coupon code",
			  	minlength:"Code shoud be between 4 to 10 caharacter",
				maxlength:"Code shoud be between 4 to 10 caharacter",
		  },
		  coupon_value:{
			  	number:"Enter valid coupon value",
			  	required:"Enter Coupon Value",
				min:"Value should be more than or equal to 1",				
				max:"Coupon discount percentage should be less than 99",
		  },
		  coupon_last_date:{			  	
			  	required:"select coupon valid last date",
		  },		  
		  coupon_occourence:{
			  	digits:"Enter valid occurence",
			  	required:"Enter occurence Value",
				min:"Value should be more than or equal to 1",
				max:"Value should be less than 100",
		  },
		  coupon_min_billing:{
			  	digits:"Enter valid min billing value",			  	
				min:"Value should be greater than or equal to 1",
				max:"Value should be less than 100000",
		  },
		  coupon_max_discount:{
			  	digits:"Enter valid max discount value",			  	
				min:"Value should be greater than or equal to 1",
				max:"Value should be less than 100000",
		  },
		  
	  }
	  
  });

</script>