<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-speech-bubble-2"> Add Coupon </span>
    </div>
    <div class="mws-panel-body">
        <form class="mws-form" method="post" enctype="multipart/form-data">
            <?php if ($this->hasMessage): ?>
                <div class="mws-form-message <?php echo $this->messageType == 'danger' ? 'error' : $this->messageType; ?> fade in">
                    <?php if ($this->messageType == "danger"): ?>
                        <strong>Oh snap!</strong>
                    <?php elseif ($this->messageType == "success"): ?>
                        <strong>Well done!</strong>
                    <?php elseif ($this->messageType == "info"): ?>
                        <strong>Heads up!</strong>
                    <?php elseif ($this->messageType == "warning"): ?>
                        <strong>Warning!</strong>
                    <?php endif; ?>
                    <?php echo $this->message; ?>
                </div>
            <?php endif; ?>

            <?php
                $elements = $this->form->getElements();
				
                foreach ($elements as $element):
                    ?>
                <div class="mws-form-inline"><div class="mws-form-row"><?php echo $element; ?></div></div>    
                    
                    <?php
                endforeach;
                ?>
                <div class="mws-button-row">
                    <input type="hidden" name="request_type" value="add">
                    <button type="submit" class="mws-button red" >Add</button>
                </div>
        </form>
    </div>
</div>
<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1"> All Services</span>
    </div>
    <div class="mws-panel-body">
        <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>
                    <th>Coupon Type</th>
                    <th>Coupon Code</th>
                    <th>Coupon Value</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->coupons): ?>
                    <?php foreach ($this->coupons as $coupon): ?>
                        <tr>
                            <td><?php echo $coupon->__get("coupon_type"); ?></td>
                            <td><?php echo $coupon->__get("coupon_code"); ?></td>
                            <td><?php echo $coupon->__get("coupon_value"); ?></td>
                            <td>
                                <?php
                                $secure = New My_Secure();
                                $id = $secure->encode($coupon->__get("coupon_id"));
                                ?>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/coupons/edit/id/<?php echo $id;?>"><button class="btn btn-warning btn-mini"><i class="icon-wrench  bigger-110 icon-only"></i> </button></a>
                                <a href="#" data-id="<?php echo $coupon->__get("coupon_id"); ?>"  class="delete"><button class="btn btn-grey btn-mini"><i class="icon-trash  icon-only"></i> </button></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>

            </tbody>
        </table>
    </div>
</div>

<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display:none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="hidden" name="request_type" value="delete"/>
                    <input type="hidden" name="id" id="delete_id" value=""/>
                    <button type="submit" class="btn btn-primary btn-danger">Confirm Delete</button>
                </div>
            </form>
        </div><!-- modal-content -->
    </div><!-- modal-dialog -->
</div>

<script type="text/javascript">
$(".mws-datepicker").datepicker({
	showOtherMonths:true,
	minDate: '0'
});

  $(".mws-form").validate({
	  
	  rules:{
		  coupon_type:{
			  	required:true,
		  },
		  coupon_code:{
			  	required:true,
			  	minlength:4,
				maxlength:10,				
		  },
		  coupon_value:{
			  	number:true,
			  	required:true,			  	
				min:1,
				
				max:{
					param: 99,
					depends: function(element) {
					  return $("#coupon_type").val()=="percentage";
					}
				},
		  },
		  coupon_last_date:{			  	
			  	required:true,			  					
		  },
		  coupon_occourence:{
			  	digits:true,
			  	required:true,			  	
				min:1,
				max:100,
		  },
		  coupon_min_billing:{
			  	digits:true,
				min:1,
				max:100000,
		  },
		  coupon_max_discount:{
			  	digits:true,			  	
				min:1,
				max:100000,
		  },
		  
		  
	  },
	  messages:{
		  coupon_type:"Please select coupon type",
		  coupon_code:{
			  	required:"Enter coupon code",
			  	minlength:"Code shoud be between 4 to 10 caharacter",
				maxlength:"Code shoud be between 4 to 10 caharacter",
		  },
		  coupon_value:{
			  	number:"Enter valid coupon value",
			  	required:"Enter Coupon Value",
				min:"Value should be more than or equal to 1",				
				max:"Coupon discount percentage should be less than 99",
		  },		  
		  coupon_last_date:{			  	
			  	required:"select coupon valid last date",
		  },
		  coupon_occourence:{
			  	digits:"Enter valid occurence",
			  	required:"Enter occurence Value",
				min:"Value should be more than or equal to 1",
				max:"Value should be less than 100",
		  },
		  coupon_min_billing:{
			  	digits:"Enter valid min billing value",			  	
				min:"Value should be greater than or equal to 1",
				max:"Value should be less than 100000",
		  },
		  coupon_max_discount:{
			  	digits:"Enter valid max discount value",			  	
				min:"Value should be greater than or equal to 1",
				max:"Value should be less than 100000",
		  },
		  
	  }
	  
  });

</script>