

<div id="slider_wrapper2">
    <div class="wrap">

        <h1>Login to your account</h1>

    </div>
</div>

<div class="clear"></div>

<div class="content" style="background:transparent">
    <div class="wrap" style="background: transparent; padding: 10px;">
        
        <p style="font-size: 25px;"><strong>Thank You for placing your order.Your Order has been recieved successfully.</strong></p>
        <div class="clear"></div>

    </div>
</div>

<div class="blue-bar">

</div>  
